project:
  type: website
  preview:
    port: 6222
    host: 0.0.0.0
    browser: false
website:
  draft-mode: gone
  navbar:
    logo: "images/dmlbl_logo.png"
    left:
      - text: Building
        href: index.qmd#building
      - text: Writing
        href: technical_blog.qmd
      - text: About
        href: about.qmd
    tools:
      - icon: file-person-fill
        href: resume.qmd
      - icon: twitter-x
        href: https://twitter.com/dmitriyleybel
      - icon: linkedin
        href: https://www.linkedin.com/in/dmlbl/
      - icon: envelope-fill
        href: "#mail"
  page-footer:
    center:
      - text: "© 2026 - Dmitriy Leybel"
      - icon: twitter-x
        href: https://twitter.com/dmitriyleybel
      - icon: linkedin
        href: https://www.linkedin.com/in/dmlbl/

  google-analytics: "G-SB4HQ6BZVQ"
  twitter-card:
    creator: "@dmitriyleybel"
  open-graph: true
  favicon: "images/favicon.ico"
  site-url: https://www.dmlbl.com
  description: "Dmitriy Leybel's personal website and technical blog"

format:
  html:
    theme:
      - superhero
      - custom.scss
    toc: true
    mainfont: "Source Sans 3"
    monofont: Inconsolata
    title-block-banner: false
    email-obfuscation: 'javascript'
    include-in-header: _includes/mail.html

resources:
  - CNAME
  - js/net.js
