project:
  type: website
  preview:
    port: 6222
website:
  navbar:
    logo: "images/dmlbl_logo.png"
    left:
      - text: Technical Blog
        href: technical_blog.qmd
      - text: Personal Blog
        href: personal_blog.qmd
      - about.qmd
    tools:
      - icon: file-person-fill
        href: resume.qmd
      - icon: twitter-x
        href: https://twitter.com/dmitriyleybel
      - icon: linkedin
        href: https://www.linkedin.com/in/dmlbl/
      - icon: envelope-fill
        href: mailto:dmleybel@gmail.com
  page-footer:
    center:
      - text: "© 2024 - Dmitriy Leybel"
      - icon: twitter-x
        href: https://twitter.com/dmitriyleybel
      - icon: linkedin
        href: https://www.linkedin.com/in/dmlbl/
  google-analytics: "G-SB4HQ6BZVQ"
  twitter-card:
    creator: "@dmitriyleybel"
  open-graph: true
  favicon: "images/favicon.ico"
  site-url: https://www.dmlbl.com
  description: "Dmitriy Leybel's personal website and technical blog"

format:
  html:
    theme:
      - superhero
      - custom.scss
    toc: true
    mainfont: Hanken Grotesk
    monofont: Inconsolata
    title-block-banner: true
    email-obfuscation: 'javascript'
  

resources:
  - CNAME



